info = [
    {
        name ="UG-保险-博观随心推-1",
        id = 1733053681002496,
        carton = "自行替换",
        cookie = "自行替换"
    },
    {
        name ="UG-短险千川-博观-3",
        id = 1729353507265543,
        carton = "自行替换",
        cookie = "自行替换"
    },
    {
        name ="UG-短险千川-博观-2",
        id = 1727260490285135,
        carton = "自行替换",
        cookie = "自行替换"
    },
    {
        name ="UG-短险千川-博观-1",
        id = 1727260489617423,
        carton = "cookie02",
        cookie = "cookie02"
    }
]
